version: '3.8'

services:
  olivka_food_bot:
    build: .
    image: "olivka_food_bot:latest"
    container_name: "olivka_food_bot"
    restart: always
    command: python app.py
    volumes:
      - ./database:/olivka_food_bot/database
    environment:
      - BOT_TOKEN=
      - ADMIN_ID=
      - FONT_LINK=utils/converter/Garet.ttf
      - LOG_LEVEL=DEBUG
      - MIDDLEWARE_BAN=15
      - PREKOL=